### PR TITLE
TabStackedNormalExercise initial commit

### PR DESCRIPTION
**Pull request by gor181**
Documentation on how to author `TabStackedNormalExercise` as per [functional specification](https://docs.google.com/document/d/1Nedi21lOxSczrPct9CJKwWa6x2BeCeS90QIWvXzY9Gk/edit#)

### CODE REVIEW

**Comment by gor181** [comment]
@ramnathv Docs at https://teach-documentation-pr-79.herokuapp.com/courses/exercises/tab-exercise.html#tab-stacked-normal-exercise

**Comment by gor181** [comment]
hey @ramnathv,

We have just deployed support for TabStackedNormalExercise to production.
I have created a new branch in your [repository](https://www.datacamp.com/teach/repositories/2246/branches/test-goran)  which contains [TabStackedNormalExercise exercise](https://github.com/datacamp/courses-exercise-types/blame/test-goran/chapter3.md#L446)

You can preview it in campus by visiting:
- [Tab Exercise](https://campus.datacamp.com/courses/7042/22332?ex=3)
- [TabStackedNormalExercise](https://campus.datacamp.com/courses/7042/22332?ex=5)

**Comment by gor181** [comment]
@ramnathv can we merge this?

cc @yashasroy

**Comment by gor181** [comment]
@ramnathv I have just been talking to @yashasroy and we were thinking about `subkeys` and `subxps`. We have a few questions:

1. Should the `xp` on the `TabStackedNormalExercise` level be equal to sum of all `xp` in `subxps`?
2. Should we generate subexercise `xp` by taking `TabStackedNormalExercise` `xp / exercise count`?
3. Is there a need to specify  the subkeys? Afaik key should be unique in the whole chapter so maybe we can just combine the key in the `TabStackedNormalExercise` with a index number of the subexercise? What concerns me here is that by doing this we cannot really re-arrange the exercises at later point?

Thanks

**Comment by ramnathv** [comment]
@gor181 My responses to the questions raised above:

1. XP should work just like in `TabExercise`, where they are specified at the sub-exercise level. The total XP for the exercise should be the sum total of XP for all sub-exercises.
2. I would not compute sub-exercise XP this way since it can result in non-rounded numbers.
3. The order of sub-exercises in a TabExercises is very unlikely to change. So, I like the idea of generating subkeys by combining the key of the exercise with an index number of the sub-exercise.

Let me know if this answers all your questions. cc @yashasroy

**Comment by gor181** [comment]
Thanks, this is great feedback. If Yashas agrees we can implement this
changes shortly.

**Comment by gor181** [comment]
@yashasroy do you agree with all statements in [comment](https://github.com/datacamp/authoring/pull/79#issuecomment-370861163) from @ramnathv ?

**Comment by yashasroy** [comment]
@gor181 Yes, I agree with all the statements (sorry for the delay in response).

**Comment by gor181** [comment]
No problems. thanks

**Comment by richierocks** [comment]
@gor181 Is this ready for review, or does the content still need updating?

**Comment by gor181** [comment]
@richierocks - I assigned that long ago for review 😄. A copy check is more than welcome

**Comment by ncarchedi** [comment]
@richierocks can you have a look at this? Seems relevant to our discussion from earlier this week.

**Comment by gvwilson** [comment]
ping - is this one still relevant, and if so, shall I review and merge?

**Pull request merged**
