### PR TITLE
Proof-reading documentation for courses

### PR DESCRIPTION
**Pull request by gvwilson**
Editing documentation on courses for style (and to make sure I understand it so that I can write a tutorial).

Question: Is pre_exercise_code in a TabExercise really executed for each sub-exercise?

### CODE REVIEW

**Comment by gvwilson** [comment]
I don't believe I've changed content in any meaningful way, but I did have one question (in the body of the PR). I have a few more files to go through, and someone will need to check that links resolve before this is published.

**Comment by ncarchedi** [comment]
@gvwilson ok, I'll wait to merge then. I don't see the question though.

**Comment by gvwilson** [comment]
https://github.com/datacamp/authoring/pull/45#issue-280540578

**Comment by ncarchedi** [comment]
Link doesn't work for me. Can you just put the question here or tell me file and line number?

**Comment by gvwilson** [comment]
?? The question is in the body of the comment made when the PR was submitted.
screen shot 2017-12-08 at 1 58 59 pm

**Comment by ncarchedi** [comment]
@gvwilson sorry, I thought you meant in the diff. I thought pre-ex code ran once for tab exercises, but worth confirming with @gor181 if it's not documented that way.

**Comment by gor181** [comment]
`pre_exercise_code` is something which is executed by LE. @rv2e Can you confirm whether `pre_exercise_code` is being executed only once for tab/bullet exercise or each time for each of the sub-exercises?

**Comment by rv2e** [comment]
@gor181 @gvwilson I've just checked because I wasn't sure at the end and every time the PEC is executed for a Tab and Bullet Exercise.
But for Tab/Bullet Console Exercise, we run the PEC only the first time.

**Comment by gvwilson** [comment]
thanks I'll update the authoring docs

**Comment by gvwilson** [comment]
Docs updated - I think this one is ready to merge.

**Comment by gvwilson** [comment]
Why the difference between `TabExercise` and `TabConsoleExercise` w.r.t. `pre_exercise_code` execution? (ditto `Bullet*`)?

**Comment by machow** [comment]
The TabConsoleExercises is basically restricted form of TabExercise. 

A TabExercise..

* can be a mixture of exercise types
* runs them in the same way as if they were independent

A TabConsoleExercise

* can only be ConsoleExercises
* is not run independently

If you want to reset a students workspace each time, use TabExercise. If you want them to retain the results of their actions, use TabConsoleExercise.

**Comment by richierocks** [comment]
In the README, when describing the 3 content types, I suppose we ought to be using the 'learn, practice, master' official terminology. Something like:

- **Courses** let students **learn** new data science material
- **Challenges** allow students to **practice** what they've learned in courses
- **Projects** provide an opportunity to **master** things in a real-world setting

**Comment by richierocks** [comment]
In the [course exercises doc](https://github.com/datacamp/authoring/blob/proofreading-courses/docs/courses/exercises/README.md) it states that `PureMultipleChoiceExercise`s don't support the `lang` YAML element.

screenshot 2017-12-12 17 28 44

However, if you create a `PureMultipleChoiceExercise` in Teach using the "new pure multiple choice" button, then you get a `lang` element. 

screenshot 2017-12-12 17 31 39


I don't know if this is a documentation error or a Teach bug.

**Comment by gor181** [comment]
@richierocks teach-bug. lang is not supported for PureMultipleChoiceExercise as such exercise doesn't require the session

**Comment by gvwilson** [comment]
Thanks for the additions and corrections - ready to merge. cc @gor181 @ncarchedi

**Pull request merged**
