### PR TITLE
Feature/courses rules

### PR DESCRIPTION
**Pull request by gor181**
- Update all the rules as per most recent changes in [rules doc](https://docs.google.com/spreadsheets/d/1-KOvOB0qPHDkWyawvgLIUJYlJEuU04AsD60NJXsET1k/edit?ts=5a6a2176#gid=106199263)
- Create anchors so the page scrolls to the rule which is failing eg https://authoring.datacamp.com/courses/guidelines.html#C1
- List all the rules and their values
- Create the how to override rules example

### CODE REVIEW

**Comment by gor181** [comment]
@ramnathv Is this mergeable?

**Comment by ramnathv** [comment]
@gor181 Sorry I have not had a chance to review this yet. Based on conversations with @rasmusab and @martijnsublime, we can push the date this goes live for projects, so there is time to ensure that everything is in order.

@rasmusab Can you go over the diagnostics and file any bug reports here so @gor181 can take note of it and make the appropriate fixes. I will do the same so that between the two of us, all issues are identified.

**Comment by gor181** [comment]
Sure, please fill the bugs at https://github.com/datacamp/teach-diagnostics/issues/54

**Comment by gor181** [comment]
> @gor181 Sorry I have not had a chance to review this yet. Based on conversations with @rasmusab and @martijnsublime, we can push the date this goes live for projects, so there is time to ensure that everything is in order.

Ok no problem.

**Comment by gor181** [comment]
I'm going to merge this. We can always improve the content.

**Pull request merged**
