### PR TITLE
Feature/projects rules

### PR DESCRIPTION
**Pull request by gor181**
- Update all the rules as per most recent changes in [rules doc](https://docs.google.com/spreadsheets/d/1-KOvOB0qPHDkWyawvgLIUJYlJEuU04AsD60NJXsET1k/edit?ts=5a6a2176#gid=38147460)
- Create anchors so the page scrolls to the rule which is failing eg https://authoring.datacamp.com/projects/projects-guidelines.html#T2
- List all the rules and their values
- Create the how to override rules example

### CODE REVIEW

**Comment by rasmusab** [comment]
I would prefer that this went into it's own page, and especially not the beginning of the project format page. Would that be ok?

**Comment by rasmusab** [comment]
Ok, so I've moved stuff around a bit.

**Comment by rasmusab** [comment]
But the actual guidelines are still missing, right?

**Comment by gor181** [comment]
@rasmusab Not sure what you mean. Guidelines (enumeration) is there telling what is enforced along with how to override.

If you want to feel free to add something you think instructors are going to find beneficial.

**Comment by rasmusab** [comment]
What I mean is that the document doesn't actually mention the guidelines in the listing, it's just the titles:

image

**Comment by gor181** [comment]
> What I mean is that the document doesn't actually mention the guidelines in the listing, it's just the titles: 

I made them as titles because then you can use `#tag` in the URL to directly navigate from teach app to rule on that page.

Maybe I can change `guidelines` to `rules` so it says `The following rules are in place on a project level`?

**Comment by rasmusab** [comment]
> I made them as titles because then you can use #tag in the URL to directly navigate from teach app to rule on that page.

That is fine, I just think we should be listing the *actual* numbers/guidelines as well. Sure, most of them are integrated in [The format of a DataCamp Project notebook](https://authoring.datacamp.com/projects/projects-format.html) but it would also be good just to have a listing somewhere.

**Comment by gor181** [comment]
Actual numbers and information how to override are there? https://teach-documentation-pr-70.herokuapp.com/projects/projects-enforced-guidelines.html

**Comment by gor181** [comment]
Aaargh! Me understand now 😄 . Ok, are we good for a first merge?

**Pull request merged**
