### PR TITLE
Remove duplicates of Premium content from TOC

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by richierocks** [comment]
@ismayc I'd be tempted to drop the "Premium Courses" section in its entirety rather than having some bits in "Creating Content" and some bits in "Premium Courses".

Especially since the Premium bit hasn't been as well maintained.  So delete the other pages from the contents pane.

**Comment by richierocks** [comment]
While you are messing around with the contents pane, it might make sense to move `premium-course-process.md` before the Design pages.

**Comment by ismayc** [comment]
@richierocks I'm beginning to wonder if we should just start from scratch with `bookdown` and have travis build the book for us... That way we can organize the files in the appropriate order and reduce the manual building of the TOC?

**Comment by richierocks** [comment]
wontfix, since we're porting the content to Intercom.

**Pull request closed without merging**
