### PR TITLE
Changing the running example for course design

### PR DESCRIPTION
**Pull request by gvwilson**
Now uses design for tree-based models in Python as running example https://github.com/datacamp/courses-tree-based-models-in-python

### CODE REVIEW

**Comment by ncarchedi** [comment]
Just quickly scanned the specs. While they seem very high quality, it looks like many of the example exercises have lots of context and more than 4 instructions, which violates the new course guidelines.

@gvwilson what do you think is the best solution? Maybe pick a few and break them down into their constituent parts? Curious to hear your thoughts.

I just want to make sure we accomplish the goal of setting instructor expectations around the amount of material that goes into each exercise so they aren't surprised come time to build the course.

**Comment by karawoo** [comment]
I recommended these specs before I knew about the new course guidelines, now I agree with you @ncarchedi. I also think the examples should ideally have reproducible code with data (maybe using built-in datasets in scikit-learn?) to emphasize that they should be runnable as-is so CLs can check them. With Elie's course I downloaded data myself, but as I work on more courses this is becoming a bottleneck as instructors don't seem to realize that the code should be complete.

**Comment by gvwilson** [comment]
I agree with both comments.

1. I've created #56 to add a mention of reproducibility to the discussion of course exercises and asked @karawoo to review.
2. I think that every time a new CD or CL is hired, one of their onboarding tasks should be to go through the example exercises and the [instructor onboarding materials](http://github.com/datacamp/instructor-onboarding), check that they are consistent with the current guidelines, and have any fixes they find reviewed by an existing CD/CL. That gets fresh eyes on the material, familiarizes them with the guidelines, and ensures that they know what's where. Thoughts?

**Comment by ncarchedi** [comment]
Any thoughts on [my comment](https://github.com/datacamp/authoring/pull/48#issuecomment-351447871)?

**Comment by gvwilson** [comment]
@ncarchedi I agree the examples should be broken down - I can do (some of) the Python ones if other people can tackle the R.

**Comment by gvwilson** [comment]
Dave Robinson's Stochastic Processes is a good spec in R.

**Comment by ismayc** [comment]
Here's a link, @gvwilson: https://github.com/datacamp/courses-psychological-methods-in-r/blob/master/example_specs.md

**Comment by ismayc** [comment]
@ncarchedi Unfortunately, since the course specs have evolved and changed quite a bit over the last few months, I’m not sure if we have a great example. I think Dave’s is pretty good on the R side but the personas are different now. Happy to take the lead on this for the R side. 

Not sure of good ones on the Python side. @LoreDirick Any suggestions?

**Comment by gvwilson** [comment]
Out of date.

**Pull request closed without merging**
